"""
Columns to select from the STAC search for pre- and post-pan band satellites.

Selected columns are the same, but selecting nir08 hrefs for pre-pan and pan for post-pan.
"""


NIR_COLUMNS_SELECT = [
    "id",
    "bbox",
    "collection",
    "properties.datetime",
    "properties.eo:cloud_cover",
    "properties.view:sun_azimuth",
    "properties.view:sun_elevation",
    "properties.platform",
    "properties.instruments",
    "properties.view:off_nadir",
    "properties.landsat:cloud_cover_land",
    "properties.landsat:wrs_type",
    "properties.landsat:wrs_path",
    "properties.landsat:wrs_row",
    "properties.landsat:scene_id",
    "properties.landsat:collection_category",
    "properties.landsat:collection_number",
    "properties.landsat:correction",
    "properties.proj:code",
    "properties.proj:shape",
    "properties.proj:transform",
    "properties.created",
    "properties.updated",
    "geometry.type",
    "geometry.coordinates",
    "assets.nir08.href",
    "assets.nir08.alternate.s3.href",
    # "assets.nir08.proj:shape",
    # "assets.nir08.proj:transform",
    "geometry",
]
PAN_COLUMNS_SELECT = [
    "id",
    "bbox",
    "collection",
    "properties.datetime",
    "properties.eo:cloud_cover",
    "properties.view:sun_azimuth",
    "properties.view:sun_elevation",
    "properties.platform",
    "properties.instruments",
    "properties.view:off_nadir",
    "properties.landsat:cloud_cover_land",
    "properties.landsat:wrs_type",
    "properties.landsat:wrs_path",
    "properties.landsat:wrs_row",
    "properties.landsat:scene_id",
    "properties.landsat:collection_category",
    "properties.landsat:collection_number",
    "properties.landsat:correction",
    "properties.proj:code",
    "properties.proj:shape",
    "properties.proj:transform",
    "properties.created",
    "properties.updated",
    "geometry.type",
    "geometry.coordinates",
    "assets.pan.href",
    "assets.pan.alternate.s3.href",
    # "assets.pan.proj:shape",
    # "assets.pan.proj:transform",
    "geometry",
]
COLUMNS_RENAME = [
    "id",
    "bbox",
    "collection",
    "datetime",
    "eo:cloud_cover",
    "view:sun_azimuth",
    "view:sun_elevation",
    "platform",
    "instruments",
    "view:off_nadir",
    "landsat:cloud_cover_land",
    "landsat:wrs_type",
    "landsat:wrs_path",
    "landsat:wrs_row",
    "landsat:scene_id",
    "landsat:collection_category",
    "landsat:collection_number",
    "landsat:correction",
    "proj:epsg",
    "proj:shape",
    "proj:transform",
    "created",
    "updated",
    "geometry.type",
    "geometry.coordinates",
    "landsatlook_href",
    "s3_href",
    # "proj:shape",
    # "proj:transform",
    "geometry",
]
